name: rivgraph
channels:  
  - conda-forge
dependencies:
  - python=3
  - geopandas
  - scikit-image
  - opencv
  - networkx <2.7 # necessary for correct numpy ops
  - shapely =1.7.1
  - matplotlib-base
  - fastdtw
  - loguru
