name: rivgraph
channels:
  - jschwenk
  - conda-forge
  - defaults
dependencies:
  - python=3
  - gdal
  - numpy
  - geopandas
  - scikit-image
  - opencv
  - networkx
  - matplotlib
  - pyproj
  - shapely
  - fiona
  - rivgraph
  - fastdtw
  - pip
  - pip:
    - loguru
