name: rivgraph
channels:
  - jschwenk
  - conda-forge
  - defaults
dependencies:
  - python=3
  - gdal
  - numpy
  - geopandas
  - scikit-image
  - opencv
  - networkx
  - matplotlib
  - pyproj
  - shapely==1.7.1
  - fiona
  - rivgraph
  - fastdtw
