name: rivgraph
channels:
  - jschwenk
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - gdal
  - numpy
  - geopandas=0.7.0
  - scikit-image
  - opencv
  - networkx
  - matplotlib
  - pyproj
  - shapely
  - fiona
  - rivgraph
  - fastdtw
